// Move the player_stats object here from players.js
const player_stats = {
  "Saquon Barkley": {
    "week 1": {
      "Rank": 0,
      "Player": "Saquon Barkley",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 25,
      "YDS.1": 119,
      "TD.1": 0,
      "FL": 0,
      "REC": 2,
      "TGT": 2,
      "YDS.2": 4,
      "TD.2": 0,
      "G": 1,
      "FPTS": 14.3,
      "FPTS/G": 14.3,
      "ROST": "89.7%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Saquon Barkley",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 26,
      "YDS.1": 205,
      "TD.1": 2,
      "FL": 0,
      "REC": 4,
      "TGT": 4,
      "YDS.2": 27,
      "TD.2": 0,
      "G": 1,
      "FPTS": 39.2,
      "FPTS/G": 39.2,
      "ROST": "89.7%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Saquon Barkley",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 15,
      "YDS.1": 118,
      "TD.1": 3,
      "FL": 0,
      "REC": 1,
      "TGT": 2,
      "YDS.2": 4,
      "TD.2": 0,
      "G": 1,
      "FPTS": 31.2,
      "FPTS/G": 31.2,
      "ROST": "89.7%",
      "POS": "wr"
    }
  },
  "Justin Jefferson": {
    "week 1": {
      "Rank": 0,
      "Player": "Justin Jefferson",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 5,
      "TGT": 8,
      "YDS.2": 58,
      "TD.2": 0,
      "G": 1,
      "FPTS": 10.8,
      "FPTS/G": 10.8,
      "ROST": "82.1%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Justin Jefferson",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "82.1%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Justin Jefferson",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "82.1%",
      "POS": "qb"
    }
  },
  "Josh Allen": {
    "week 1": {
      "Rank": 0,
      "Player": "Josh Allen",
      "CMP": 20,
      "ATT": 26,
      "PCT": 76.9,
      "YDS": 272,
      "TD": 2,
      "INT": 0,
      "ATT.1": 8,
      "YDS.1": 46,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 23.5,
      "FPTS/G": 23.5,
      "ROST": "79.5%",
      "POS": "rb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Josh Allen",
      "CMP": 16,
      "ATT": 22,
      "PCT": 72.7,
      "YDS": 127,
      "TD": 0,
      "INT": 0,
      "ATT.1": 10,
      "YDS.1": 20,
      "TD.1": 2,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 19.1,
      "FPTS/G": 19.1,
      "ROST": "79.5%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Josh Allen",
      "CMP": 22,
      "ATT": 34,
      "PCT": 64.7,
      "YDS": 237,
      "TD": 2,
      "INT": 0,
      "ATT.1": 11,
      "YDS.1": 39,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 21.4,
      "FPTS/G": 21.4,
      "ROST": "79.5%",
      "POS": "qb"
    }
  },
  "Jahmyr Gibbs": {
    "week 1": {
      "Rank": 0,
      "Player": "Jahmyr Gibbs",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "61.5%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Jahmyr Gibbs",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 14,
      "YDS.1": 105,
      "TD.1": 2,
      "FL": 0,
      "REC": 6,
      "TGT": 11,
      "YDS.2": 70,
      "TD.2": 0,
      "G": 1,
      "FPTS": 35.5,
      "FPTS/G": 35.5,
      "ROST": "61.5%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Jahmyr Gibbs",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "61.5%",
      "POS": "qb"
    }
  },
  "Lamar Jackson": {
    "week 1": {
      "Rank": 0,
      "Player": "Lamar Jackson",
      "CMP": 16,
      "ATT": 21,
      "PCT": 76.2,
      "YDS": 175,
      "TD": 2,
      "INT": 0,
      "ATT.1": 15,
      "YDS.1": 81,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 23.1,
      "FPTS/G": 23.1,
      "ROST": "51.3%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Lamar Jackson",
      "CMP": 18,
      "ATT": 25,
      "PCT": 72.0,
      "YDS": 254,
      "TD": 2,
      "INT": 1,
      "ATT.1": 6,
      "YDS.1": 39,
      "TD.1": 0,
      "FL": 1,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 19.1,
      "FPTS/G": 19.1,
      "ROST": "51.3%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Lamar Jackson",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "51.3%",
      "POS": "qb"
    }
  },
  "Derrick Henry": {
    "week 1": {
      "Rank": 0,
      "Player": "Derrick Henry",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 26,
      "YDS.1": 186,
      "TD.1": 2,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 30.6,
      "FPTS/G": 30.6,
      "ROST": "48.7%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Derrick Henry",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 16,
      "YDS.1": 84,
      "TD.1": 1,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 14.4,
      "FPTS/G": 14.4,
      "ROST": "48.7%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Derrick Henry",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "48.7%",
      "POS": "qb"
    }
  },
  "Chris Boswell": {
    "week 1": {
      "Rank": 0,
      "Player": "Chris Boswell",
      "FPTS": 2,
      "FPTS/G": 2,
      "ROST": "48.7%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Chris Boswell",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "48.7%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Chris Boswell",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "48.7%",
      "POS": "k"
    }
  },
  "Denver Broncos": {
    "week 1": {
      "Rank": 0,
      "Player": "Denver Broncos",
      "SACKS": 2.0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 31,
      "G": 1,
      "FPTS": 1.0,
      "FPTS/G": 1.0,
      "ROST": "48.7%",
      "POS": "def"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Denver Broncos",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "48.7%",
      "POS": "def"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Denver Broncos",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "48.7%",
      "POS": "def"
    }
  },
  "Puka Nacua": {
    "week 1": {
      "Rank": 0,
      "Player": "Puka Nacua",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 1,
      "YDS.1": 7,
      "TD.1": 0,
      "FL": 0,
      "REC": 5,
      "TGT": 9,
      "YDS.2": 44,
      "TD.2": 0,
      "G": 1,
      "FPTS": 10.1,
      "FPTS/G": 10.1,
      "ROST": "48.7%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Puka Nacua",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 6,
      "TGT": 14,
      "YDS.2": 97,
      "TD.2": 0,
      "G": 1,
      "FPTS": 15.7,
      "FPTS/G": 15.7,
      "ROST": "48.7%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Puka Nacua",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "48.7%",
      "POS": "qb"
    }
  },
  "Bucky Irving": {
    "week 1": {
      "Rank": 0,
      "Player": "Bucky Irving",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 17,
      "YDS.1": 77,
      "TD.1": 0,
      "FL": 0,
      "REC": 2,
      "TGT": 2,
      "YDS.2": 6,
      "TD.2": 1,
      "G": 1,
      "FPTS": 16.3,
      "FPTS/G": 16.3,
      "ROST": "46.2%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Bucky Irving",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "46.2%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Bucky Irving",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "46.2%",
      "POS": "qb"
    }
  },
  "Ladd McConkey": {
    "week 1": {
      "Rank": 0,
      "Player": "Ladd McConkey",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 9,
      "TGT": 14,
      "YDS.2": 197,
      "TD.2": 1,
      "G": 1,
      "FPTS": 34.7,
      "FPTS/G": 34.7,
      "ROST": "46.2%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Ladd McConkey",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "46.2%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Ladd McConkey",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "46.2%",
      "POS": "qb"
    }
  },
  "Josh Jacobs": {
    "week 1": {
      "Rank": 0,
      "Player": "Josh Jacobs",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 18,
      "YDS.1": 81,
      "TD.1": 1,
      "FL": 0,
      "REC": 3,
      "TGT": 3,
      "YDS.2": 40,
      "TD.2": 0,
      "G": 1,
      "FPTS": 21.1,
      "FPTS/G": 21.1,
      "ROST": "43.6%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Josh Jacobs",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "43.6%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Josh Jacobs",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "43.6%",
      "POS": "qb"
    }
  },
  "Terry McLaurin": {
    "week 1": {
      "Rank": 0,
      "Player": "Terry McLaurin",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 7,
      "TGT": 10,
      "YDS.2": 89,
      "TD.2": 1,
      "G": 1,
      "FPTS": 21.9,
      "FPTS/G": 21.9,
      "ROST": "41.0%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Terry McLaurin",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 4,
      "TGT": 6,
      "YDS.2": 87,
      "TD.2": 1,
      "G": 1,
      "FPTS": 18.7,
      "FPTS/G": 18.7,
      "ROST": "41.0%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Terry McLaurin",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 3,
      "TGT": 7,
      "YDS.2": 51,
      "TD.2": 1,
      "G": 1,
      "FPTS": 14.1,
      "FPTS/G": 14.1,
      "ROST": "41.0%",
      "POS": "wr"
    }
  },
  "Nico Collins": {
    "week 1": {
      "Rank": 0,
      "Player": "Nico Collins",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 7,
      "TGT": 8,
      "YDS.2": 122,
      "TD.2": 1,
      "G": 1,
      "FPTS": 25.2,
      "FPTS/G": 25.2,
      "ROST": "38.5%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Nico Collins",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 5,
      "TGT": 8,
      "YDS.2": 81,
      "TD.2": 0,
      "G": 1,
      "FPTS": 13.1,
      "FPTS/G": 13.1,
      "ROST": "38.5%",
      "POS": "wr"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Nico Collins",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "38.5%",
      "POS": "qb"
    }
  },
  "Brandon McManus": {
    "week 1": {
      "Rank": 0,
      "Player": "Brandon McManus",
      "FPTS": 2,
      "FPTS/G": 2,
      "ROST": "38.5%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Brandon McManus",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "38.5%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Brandon McManus",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "38.5%",
      "POS": "k"
    }
  },
  "Travis Kelce": {
    "week 1": {
      "Rank": 0,
      "Player": "Travis Kelce",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "35.9%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Travis Kelce",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 7,
      "TGT": 8,
      "YDS.2": 117,
      "TD.2": 1,
      "G": 1,
      "FPTS": 24.7,
      "FPTS/G": 24.7,
      "ROST": "35.9%",
      "POS": "wr"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Travis Kelce",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 2,
      "TGT": 4,
      "YDS.2": 19,
      "TD.2": 0,
      "G": 1,
      "FPTS": 3.9,
      "FPTS/G": 3.9,
      "ROST": "35.9%",
      "POS": "qb"
    }
  },
  "Wil Lutz": {
    "week 1": {
      "Rank": 0,
      "Player": "Wil Lutz",
      "FPTS": 1,
      "FPTS/G": 1,
      "ROST": "35.9%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Wil Lutz",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "35.9%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Wil Lutz",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "35.9%",
      "POS": "k"
    }
  },
  "Pittsburgh Steelers": {
    "week 1": {
      "Rank": 0,
      "Player": "Pittsburgh Steelers",
      "SACKS": 1.0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 28,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "35.9%",
      "POS": "def"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Pittsburgh Steelers",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "35.9%",
      "POS": "def"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Pittsburgh Steelers",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "35.9%",
      "POS": "def"
    }
  },
  "Kyren Williams": {
    "week 1": {
      "Rank": 0,
      "Player": "Kyren Williams",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 16,
      "YDS.1": 76,
      "TD.1": 0,
      "FL": 0,
      "REC": 3,
      "TGT": 3,
      "YDS.2": 16,
      "TD.2": 1,
      "G": 1,
      "FPTS": 18.2,
      "FPTS/G": 18.2,
      "ROST": "25.6%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Kyren Williams",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 19,
      "YDS.1": 106,
      "TD.1": 0,
      "FL": 1,
      "REC": 1,
      "TGT": 2,
      "YDS.2": -1,
      "TD.2": 0,
      "G": 1,
      "FPTS": 9.5,
      "FPTS/G": 9.5,
      "ROST": "25.6%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Kyren Williams",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "25.6%",
      "POS": "qb"
    }
  },
  "Jared Goff": {
    "week 1": {
      "Rank": 0,
      "Player": "Jared Goff",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "23.1%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Jared Goff",
      "CMP": 23,
      "ATT": 40,
      "PCT": 57.5,
      "YDS": 313,
      "TD": 1,
      "INT": 3,
      "ATT.1": 1,
      "YDS.1": 7,
      "TD.1": 0,
      "FL": 1,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 12.2,
      "FPTS/G": 12.2,
      "ROST": "23.1%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Jared Goff",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "23.1%",
      "POS": "qb"
    }
  },
  "Washington Commanders": {
    "week 1": {
      "Rank": 0,
      "Player": "Washington Commanders",
      "SACKS": 1.0,
      "FR": 1,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 20,
      "G": 1,
      "FPTS": 4.0,
      "FPTS/G": 4.0,
      "ROST": "23.1%",
      "POS": "def"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Washington Commanders",
      "SACKS": 2.0,
      "FR": 1,
      "INT.1": 4,
      "TD.3": 1,
      "BK": 0,
      "SAFE": 0,
      "PA": 31,
      "G": 1,
      "FPTS": 17.0,
      "FPTS/G": 17.0,
      "ROST": "23.1%",
      "POS": "def"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Washington Commanders",
      "SACKS": 2.0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 55,
      "G": 1,
      "FPTS": -2.0,
      "FPTS/G": -2.0,
      "ROST": "23.1%",
      "POS": "def"
    }
  },
  "Patrick Mahomes II": {
    "week 1": {
      "Rank": 0,
      "Player": "Patrick Mahomes II",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "23.1%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Patrick Mahomes II",
      "CMP": 16,
      "ATT": 25,
      "PCT": 64.0,
      "YDS": 177,
      "TD": 1,
      "INT": 0,
      "ATT.1": 7,
      "YDS.1": 14,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 12.5,
      "FPTS/G": 12.5,
      "ROST": "23.1%",
      "POS": "rb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Patrick Mahomes II",
      "CMP": 18,
      "ATT": 26,
      "PCT": 69.2,
      "YDS": 245,
      "TD": 1,
      "INT": 0,
      "ATT.1": 11,
      "YDS.1": 43,
      "TD.1": 2,
      "FL": 1,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 28.1,
      "FPTS/G": 28.1,
      "ROST": "23.1%",
      "POS": "qb"
    }
  },
  "Mike Evans": {
    "week 1": {
      "Rank": 0,
      "Player": "Mike Evans",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 7,
      "TGT": 7,
      "YDS.2": 92,
      "TD.2": 1,
      "G": 1,
      "FPTS": 22.2,
      "FPTS/G": 22.2,
      "ROST": "23.1%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Mike Evans",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "23.1%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Mike Evans",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "23.1%",
      "POS": "qb"
    }
  },
  "Los Angeles Chargers": {
    "week 1": {
      "Rank": 0,
      "Player": "Los Angeles Chargers",
      "SACKS": 3.0,
      "FR": 2,
      "INT.1": 1,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 32,
      "G": 1,
      "FPTS": 8.0,
      "FPTS/G": 8.0,
      "ROST": "23.1%",
      "POS": "def"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Los Angeles Chargers",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "23.1%",
      "POS": "def"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Los Angeles Chargers",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "23.1%",
      "POS": "def"
    }
  },
  "Houston Texans": {
    "week 1": {
      "Rank": 0,
      "Player": "Houston Texans",
      "SACKS": 4.0,
      "FR": 0,
      "INT.1": 4,
      "TD.3": 1,
      "BK": 0,
      "SAFE": 0,
      "PA": 12,
      "G": 1,
      "FPTS": 22.0,
      "FPTS/G": 22.0,
      "ROST": "20.5%",
      "POS": "def"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Houston Texans",
      "SACKS": 3.0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 1,
      "PA": 23,
      "G": 1,
      "FPTS": 5.0,
      "FPTS/G": 5.0,
      "ROST": "20.5%",
      "POS": "def"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Houston Texans",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "20.5%",
      "POS": "def"
    }
  },
  "Joe Mixon": {
    "week 1": {
      "Rank": 0,
      "Player": "Joe Mixon",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 25,
      "YDS.1": 106,
      "TD.1": 1,
      "FL": 1,
      "REC": 1,
      "TGT": 2,
      "YDS.2": 13,
      "TD.2": 0,
      "G": 1,
      "FPTS": 16.9,
      "FPTS/G": 16.9,
      "ROST": "20.5%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Joe Mixon",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 18,
      "YDS.1": 88,
      "TD.1": 1,
      "FL": 0,
      "REC": 2,
      "TGT": 3,
      "YDS.2": 12,
      "TD.2": 0,
      "G": 1,
      "FPTS": 18.0,
      "FPTS/G": 18.0,
      "ROST": "20.5%",
      "POS": "wr"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Joe Mixon",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "20.5%",
      "POS": "qb"
    }
  },
  "Ka'imi Fairbairn": {
    "week 1": {
      "Rank": 0,
      "Player": "Ka'imi Fairbairn",
      "FPTS": 13,
      "FPTS/G": 13,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Ka'imi Fairbairn",
      "FPTS": 11,
      "FPTS/G": 11,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Ka'imi Fairbairn",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "17.9%",
      "POS": "k"
    }
  },
  "Cameron Dicker": {
    "week 1": {
      "Rank": 0,
      "Player": "Cameron Dicker",
      "FPTS": 6,
      "FPTS/G": 6,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Cameron Dicker",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Cameron Dicker",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "17.9%",
      "POS": "k"
    }
  },
  "Zane Gonzalez": {
    "week 1": {
      "Rank": 0,
      "Player": "Zane Gonzalez",
      "FPTS": 11,
      "FPTS/G": 11,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Zane Gonzalez",
      "FPTS": 8,
      "FPTS/G": 8,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Zane Gonzalez",
      "FPTS": 11,
      "FPTS/G": 11,
      "ROST": "17.9%",
      "POS": "k"
    }
  },
  "James Cook": {
    "week 1": {
      "Rank": 0,
      "Player": "James Cook",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 23,
      "YDS.1": 120,
      "TD.1": 1,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 18.0,
      "FPTS/G": 18.0,
      "ROST": "17.9%",
      "POS": "rb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "James Cook",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 17,
      "YDS.1": 67,
      "TD.1": 0,
      "FL": 0,
      "REC": 3,
      "TGT": 3,
      "YDS.2": 15,
      "TD.2": 0,
      "G": 1,
      "FPTS": 11.2,
      "FPTS/G": 11.2,
      "ROST": "17.9%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "James Cook",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 13,
      "YDS.1": 85,
      "TD.1": 2,
      "FL": 0,
      "REC": 3,
      "TGT": 3,
      "YDS.2": 49,
      "TD.2": 0,
      "G": 1,
      "FPTS": 28.4,
      "FPTS/G": 28.4,
      "ROST": "17.9%",
      "POS": "qb"
    }
  },
  "Amon-Ra St. Brown": {
    "week 1": {
      "Rank": 0,
      "Player": "Amon-Ra St. Brown",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "15.4%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Amon-Ra St. Brown",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 8,
      "TGT": 10,
      "YDS.2": 137,
      "TD.2": 0,
      "G": 1,
      "FPTS": 21.7,
      "FPTS/G": 21.7,
      "ROST": "15.4%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Amon-Ra St. Brown",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "15.4%",
      "POS": "qb"
    }
  },
  "J.K. Dobbins": {
    "week 1": {
      "Rank": 0,
      "Player": "J.K. Dobbins",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 9,
      "YDS.1": 26,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 2.6,
      "FPTS/G": 2.6,
      "ROST": "12.8%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "J.K. Dobbins",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "12.8%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "J.K. Dobbins",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "12.8%",
      "POS": "qb"
    }
  },
  "Green Bay Packers": {
    "week 1": {
      "Rank": 0,
      "Player": "Green Bay Packers",
      "SACKS": 2.0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 22,
      "G": 1,
      "FPTS": 2.0,
      "FPTS/G": 2.0,
      "ROST": "12.8%",
      "POS": "def"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Green Bay Packers",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "12.8%",
      "POS": "def"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Green Bay Packers",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "12.8%",
      "POS": "def"
    }
  },
  "Courtland Sutton": {
    "week 1": {
      "Rank": 0,
      "Player": "Courtland Sutton",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 5,
      "TGT": 9,
      "YDS.2": 75,
      "TD.2": 0,
      "G": 1,
      "FPTS": 12.5,
      "FPTS/G": 12.5,
      "ROST": "12.8%",
      "POS": "wr"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Courtland Sutton",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "12.8%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Courtland Sutton",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "12.8%",
      "POS": "qb"
    }
  },
  "Kansas City Chiefs": {
    "week 1": {
      "Rank": 0,
      "Player": "Kansas City Chiefs",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "12.8%",
      "POS": "def"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Kansas City Chiefs",
      "SACKS": 8.0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 14,
      "G": 1,
      "FPTS": 9.0,
      "FPTS/G": 9.0,
      "ROST": "12.8%",
      "POS": "def"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Kansas City Chiefs",
      "SACKS": 2.0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 29,
      "G": 1,
      "FPTS": 1.0,
      "FPTS/G": 1.0,
      "ROST": "12.8%",
      "POS": "def"
    }
  },
  "Los Angeles Rams": {
    "week 1": {
      "Rank": 0,
      "Player": "Los Angeles Rams",
      "SACKS": 9.0,
      "FR": 1,
      "INT.1": 1,
      "TD.3": 1,
      "BK": 0,
      "SAFE": 0,
      "PA": 9,
      "G": 1,
      "FPTS": 23.0,
      "FPTS/G": 23.0,
      "ROST": "10.3%",
      "POS": "def"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Los Angeles Rams",
      "SACKS": 7.0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 1,
      "PA": 28,
      "G": 1,
      "FPTS": 8.0,
      "FPTS/G": 8.0,
      "ROST": "10.3%",
      "POS": "def"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Los Angeles Rams",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "10.3%",
      "POS": "def"
    }
  },
  "Xavier Worthy": {
    "week 1": {
      "Rank": 0,
      "Player": "Xavier Worthy",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "10.3%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Xavier Worthy",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 1,
      "YDS.1": -8,
      "TD.1": 0,
      "FL": 0,
      "REC": 5,
      "TGT": 6,
      "YDS.2": 45,
      "TD.2": 0,
      "G": 1,
      "FPTS": 8.7,
      "FPTS/G": 8.7,
      "ROST": "10.3%",
      "POS": "wr"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Xavier Worthy",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 2,
      "YDS.1": 16,
      "TD.1": 0,
      "FL": 0,
      "REC": 6,
      "TGT": 7,
      "YDS.2": 85,
      "TD.2": 1,
      "G": 1,
      "FPTS": 22.1,
      "FPTS/G": 22.1,
      "ROST": "10.3%",
      "POS": "qb"
    }
  },
  "Cooper Kupp": {
    "week 1": {
      "Rank": 0,
      "Player": "Cooper Kupp",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 1,
      "TGT": 1,
      "YDS.2": 29,
      "TD.2": 0,
      "G": 1,
      "FPTS": 3.9,
      "FPTS/G": 3.9,
      "ROST": "10.3%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Cooper Kupp",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 5,
      "TGT": 7,
      "YDS.2": 61,
      "TD.2": 0,
      "G": 1,
      "FPTS": 11.1,
      "FPTS/G": 11.1,
      "ROST": "10.3%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Cooper Kupp",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "10.3%",
      "POS": "qb"
    }
  },
  "Baker Mayfield": {
    "week 1": {
      "Rank": 0,
      "Player": "Baker Mayfield",
      "CMP": 15,
      "ATT": 18,
      "PCT": 83.3,
      "YDS": 185,
      "TD": 2,
      "INT": 0,
      "ATT.1": 7,
      "YDS.1": 23,
      "TD.1": 0,
      "FL": 1,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 15.7,
      "FPTS/G": 15.7,
      "ROST": "10.3%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Baker Mayfield",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "10.3%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Baker Mayfield",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "10.3%",
      "POS": "qb"
    }
  },
  "George Pickens": {
    "week 1": {
      "Rank": 0,
      "Player": "George Pickens",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 5,
      "TGT": 5,
      "YDS.2": 87,
      "TD.2": 1,
      "G": 1,
      "FPTS": 19.7,
      "FPTS/G": 19.7,
      "ROST": "10.3%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "George Pickens",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "10.3%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "George Pickens",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "10.3%",
      "POS": "qb"
    }
  },
  "Chase McLaughlin": {
    "week 1": {
      "Rank": 0,
      "Player": "Chase McLaughlin",
      "FPTS": 10,
      "FPTS/G": 10,
      "ROST": "10.3%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Chase McLaughlin",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "10.3%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Chase McLaughlin",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "10.3%",
      "POS": "k"
    }
  },
  "Jayden Daniels": {
    "week 1": {
      "Rank": 0,
      "Player": "Jayden Daniels",
      "CMP": 24,
      "ATT": 35,
      "PCT": 68.6,
      "YDS": 268,
      "TD": 2,
      "INT": 0,
      "ATT.1": 13,
      "YDS.1": 36,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 22.3,
      "FPTS/G": 22.3,
      "ROST": "7.7%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Jayden Daniels",
      "CMP": 22,
      "ATT": 31,
      "PCT": 71.0,
      "YDS": 299,
      "TD": 2,
      "INT": 0,
      "ATT.1": 16,
      "YDS.1": 51,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 25.1,
      "FPTS/G": 25.1,
      "ROST": "7.7%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Jayden Daniels",
      "CMP": 29,
      "ATT": 48,
      "PCT": 60.4,
      "YDS": 255,
      "TD": 1,
      "INT": 1,
      "ATT.1": 6,
      "YDS.1": 48,
      "TD.1": 1,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 24.0,
      "FPTS/G": 24.0,
      "ROST": "7.7%",
      "POS": "rb"
    }
  },
  "Tampa Bay Buccaneers": {
    "week 1": {
      "Rank": 0,
      "Player": "Tampa Bay Buccaneers",
      "SACKS": 1.0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 23,
      "G": 1,
      "FPTS": 1.0,
      "FPTS/G": 1.0,
      "ROST": "7.7%",
      "POS": "def"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Tampa Bay Buccaneers",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "7.7%",
      "POS": "def"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Tampa Bay Buccaneers",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "7.7%",
      "POS": "def"
    }
  },
  "Jalen Hurts": {
    "week 1": {
      "Rank": 0,
      "Player": "Jalen Hurts",
      "CMP": 13,
      "ATT": 21,
      "PCT": 61.9,
      "YDS": 131,
      "TD": 2,
      "INT": 0,
      "ATT.1": 6,
      "YDS.1": 36,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 16.8,
      "FPTS/G": 16.8,
      "ROST": "5.1%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Jalen Hurts",
      "CMP": 15,
      "ATT": 20,
      "PCT": 75.0,
      "YDS": 128,
      "TD": 0,
      "INT": 0,
      "ATT.1": 7,
      "YDS.1": 70,
      "TD.1": 1,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 18.1,
      "FPTS/G": 18.1,
      "ROST": "5.1%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Jalen Hurts",
      "CMP": 20,
      "ATT": 28,
      "PCT": 71.4,
      "YDS": 246,
      "TD": 1,
      "INT": 0,
      "ATT.1": 10,
      "YDS.1": 16,
      "TD.1": 3,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 33.4,
      "FPTS/G": 33.4,
      "ROST": "5.1%",
      "POS": "rb"
    }
  },
  "Kareem Hunt": {
    "week 1": {
      "Rank": 0,
      "Player": "Kareem Hunt",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "5.1%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Kareem Hunt",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 8,
      "YDS.1": 44,
      "TD.1": 1,
      "FL": 0,
      "REC": 1,
      "TGT": 1,
      "YDS.2": 2,
      "TD.2": 0,
      "G": 1,
      "FPTS": 11.6,
      "FPTS/G": 11.6,
      "ROST": "5.1%",
      "POS": "wr"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Kareem Hunt",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 17,
      "YDS.1": 64,
      "TD.1": 1,
      "FL": 0,
      "REC": 1,
      "TGT": 1,
      "YDS.2": 6,
      "TD.2": 0,
      "G": 1,
      "FPTS": 14.0,
      "FPTS/G": 14.0,
      "ROST": "5.1%",
      "POS": "qb"
    }
  },
  "Najee Harris": {
    "week 1": {
      "Rank": 0,
      "Player": "Najee Harris",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 6,
      "YDS.1": 17,
      "TD.1": 0,
      "FL": 0,
      "REC": 3,
      "TGT": 3,
      "YDS.2": 41,
      "TD.2": 0,
      "G": 1,
      "FPTS": 8.8,
      "FPTS/G": 8.8,
      "ROST": "5.1%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Najee Harris",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "5.1%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Najee Harris",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "5.1%",
      "POS": "qb"
    }
  },
  "Joshua Karty": {
    "week 1": {
      "Rank": 0,
      "Player": "Joshua Karty",
      "FPTS": 10,
      "FPTS/G": 10,
      "ROST": "5.1%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Joshua Karty",
      "FPTS": 8,
      "FPTS/G": 8,
      "ROST": "5.1%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Joshua Karty",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "5.1%",
      "POS": "k"
    }
  },
  "Wil Reichard": {
    "week 1": {
      "Rank": 0,
      "Player": "Wil Reichard",
      "FPTS": 3,
      "FPTS/G": 3,
      "ROST": "5.1%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Wil Reichard",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "5.1%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Wil Reichard",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "5.1%",
      "POS": "k"
    }
  },
  "Isiah Pacheco": {
    "week 1": {
      "Rank": 0,
      "Player": "Isiah Pacheco",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "5.1%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Isiah Pacheco",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 5,
      "YDS.1": 18,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 1.8,
      "FPTS/G": 1.8,
      "ROST": "5.1%",
      "POS": "rb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Isiah Pacheco",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 5,
      "YDS.1": 12,
      "TD.1": 0,
      "FL": 0,
      "REC": 2,
      "TGT": 2,
      "YDS.2": 12,
      "TD.2": 0,
      "G": 1,
      "FPTS": 4.4,
      "FPTS/G": 4.4,
      "ROST": "5.1%",
      "POS": "qb"
    }
  },
  "Minnesota Vikings": {
    "week 1": {
      "Rank": 0,
      "Player": "Minnesota Vikings",
      "SACKS": 2.0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 27,
      "G": 1,
      "FPTS": 2.0,
      "FPTS/G": 2.0,
      "ROST": "5.1%",
      "POS": "def"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Minnesota Vikings",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "5.1%",
      "POS": "def"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Minnesota Vikings",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "5.1%",
      "POS": "def"
    }
  },
  "Brian Robinson Jr.": {
    "week 1": {
      "Rank": 0,
      "Player": "Brian Robinson Jr.",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 10,
      "YDS.1": 16,
      "TD.1": 0,
      "FL": 0,
      "REC": 4,
      "TGT": 5,
      "YDS.2": 22,
      "TD.2": 0,
      "G": 1,
      "FPTS": 7.8,
      "FPTS/G": 7.8,
      "ROST": "5.1%",
      "POS": "rb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Brian Robinson Jr.",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 15,
      "YDS.1": 77,
      "TD.1": 2,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 19.7,
      "FPTS/G": 19.7,
      "ROST": "5.1%",
      "POS": "rb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Brian Robinson Jr.",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 11,
      "YDS.1": 36,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 3.6,
      "FPTS/G": 3.6,
      "ROST": "5.1%",
      "POS": "rb"
    }
  },
  "Austin Ekeler": {
    "week 1": {
      "Rank": 0,
      "Player": "Austin Ekeler",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 8,
      "YDS.1": 27,
      "TD.1": 0,
      "FL": 0,
      "REC": 3,
      "TGT": 4,
      "YDS.2": 26,
      "TD.2": 0,
      "G": 1,
      "FPTS": 8.3,
      "FPTS/G": 8.3,
      "ROST": "5.1%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Austin Ekeler",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 6,
      "YDS.1": 47,
      "TD.1": 0,
      "FL": 0,
      "REC": 4,
      "TGT": 4,
      "YDS.2": 41,
      "TD.2": 0,
      "G": 1,
      "FPTS": 12.8,
      "FPTS/G": 12.8,
      "ROST": "5.1%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Austin Ekeler",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 8,
      "YDS.1": 15,
      "TD.1": 0,
      "FL": 1,
      "REC": 5,
      "TGT": 7,
      "YDS.2": 17,
      "TD.2": 0,
      "G": 1,
      "FPTS": 6.2,
      "FPTS/G": 6.2,
      "ROST": "5.1%",
      "POS": "wr"
    }
  },
  "Jordan Addison": {
    "week 1": {
      "Rank": 0,
      "Player": "Jordan Addison",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 3,
      "TGT": 8,
      "YDS.2": 29,
      "TD.2": 0,
      "G": 1,
      "FPTS": 5.9,
      "FPTS/G": 5.9,
      "ROST": "5.1%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Jordan Addison",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "5.1%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Jordan Addison",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "5.1%",
      "POS": "qb"
    }
  },
  "Aaron Jones": {
    "week 1": {
      "Rank": 0,
      "Player": "Aaron Jones",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 13,
      "YDS.1": 48,
      "TD.1": 0,
      "FL": 0,
      "REC": 3,
      "TGT": 6,
      "YDS.2": 12,
      "TD.2": 0,
      "G": 1,
      "FPTS": 9.0,
      "FPTS/G": 9.0,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Aaron Jones",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Aaron Jones",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "Diontae Johnson": {
    "week 1": {
      "Rank": 0,
      "Player": "Diontae Johnson",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 1,
      "TGT": 1,
      "YDS.2": 12,
      "TD.2": 0,
      "G": 1,
      "FPTS": 2.2,
      "FPTS/G": 2.2,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Diontae Johnson",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Diontae Johnson",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "Tucker Kraft": {
    "week 1": {
      "Rank": 0,
      "Player": "Tucker Kraft",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 2,
      "YDS.1": 10,
      "TD.1": 0,
      "FL": 0,
      "REC": 5,
      "TGT": 5,
      "YDS.2": 26,
      "TD.2": 0,
      "G": 1,
      "FPTS": 8.6,
      "FPTS/G": 8.6,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Tucker Kraft",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Tucker Kraft",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "Romeo Doubs": {
    "week 1": {
      "Rank": 0,
      "Player": "Romeo Doubs",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 2,
      "TGT": 2,
      "YDS.2": 13,
      "TD.2": 0,
      "G": 1,
      "FPTS": 3.3,
      "FPTS/G": 3.3,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Romeo Doubs",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Romeo Doubs",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "Javonte Williams": {
    "week 1": {
      "Rank": 0,
      "Player": "Javonte Williams",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 7,
      "YDS.1": 29,
      "TD.1": 0,
      "FL": 0,
      "REC": 2,
      "TGT": 2,
      "YDS.2": 14,
      "TD.2": 0,
      "G": 1,
      "FPTS": 6.3,
      "FPTS/G": 6.3,
      "ROST": "2.6%",
      "POS": "wr"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Javonte Williams",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Javonte Williams",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "Amari Cooper": {
    "week 1": {
      "Rank": 0,
      "Player": "Amari Cooper",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 2,
      "TGT": 3,
      "YDS.2": 8,
      "TD.2": 0,
      "G": 1,
      "FPTS": 2.8,
      "FPTS/G": 2.8,
      "ROST": "2.6%",
      "POS": "wr"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Amari Cooper",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Amari Cooper",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 4,
      "TGT": 4,
      "YDS.2": 33,
      "TD.2": 0,
      "G": 1,
      "FPTS": 7.3,
      "FPTS/G": 7.3,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "Harrison Butker": {
    "week 1": {
      "Rank": 0,
      "Player": "Harrison Butker",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "2.6%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Harrison Butker",
      "FPTS": 11,
      "FPTS/G": 11,
      "ROST": "2.6%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Harrison Butker",
      "FPTS": 5,
      "FPTS/G": 5,
      "ROST": "2.6%",
      "POS": "k"
    }
  },
  "A.J. Brown": {
    "week 1": {
      "Rank": 0,
      "Player": "A.J. Brown",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 1,
      "TGT": 3,
      "YDS.2": 10,
      "TD.2": 0,
      "G": 1,
      "FPTS": 2.0,
      "FPTS/G": 2.0,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "A.J. Brown",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 2,
      "TGT": 7,
      "YDS.2": 14,
      "TD.2": 0,
      "G": 1,
      "FPTS": 3.4,
      "FPTS/G": 3.4,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "A.J. Brown",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 6,
      "TGT": 8,
      "YDS.2": 96,
      "TD.2": 1,
      "G": 1,
      "FPTS": 21.6,
      "FPTS/G": 21.6,
      "ROST": "2.6%",
      "POS": "wr"
    }
  },
  "JuJu Smith-Schuster": {
    "week 1": {
      "Rank": 0,
      "Player": "JuJu Smith-Schuster",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "JuJu Smith-Schuster",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "JuJu Smith-Schuster",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 2,
      "TGT": 3,
      "YDS.2": 60,
      "TD.2": 0,
      "G": 1,
      "FPTS": 8.0,
      "FPTS/G": 8.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "DeVonta Smith": {
    "week 1": {
      "Rank": 0,
      "Player": "DeVonta Smith",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 4,
      "TGT": 4,
      "YDS.2": 55,
      "TD.2": 0,
      "G": 1,
      "FPTS": 9.5,
      "FPTS/G": 9.5,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "DeVonta Smith",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 4,
      "TGT": 4,
      "YDS.2": 21,
      "TD.2": 0,
      "G": 1,
      "FPTS": 6.1,
      "FPTS/G": 6.1,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "DeVonta Smith",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 4,
      "TGT": 4,
      "YDS.2": 45,
      "TD.2": 0,
      "G": 1,
      "FPTS": 8.5,
      "FPTS/G": 8.5,
      "ROST": "2.6%",
      "POS": "wr"
    }
  },
  "DeAndre Hopkins": {
    "week 1": {
      "Rank": 0,
      "Player": "DeAndre Hopkins",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "DeAndre Hopkins",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "DeAndre Hopkins",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 1,
      "TGT": 2,
      "YDS.2": 11,
      "TD.2": 0,
      "G": 1,
      "FPTS": 2.1,
      "FPTS/G": 2.1,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "Rachaad White": {
    "week 1": {
      "Rank": 0,
      "Player": "Rachaad White",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 1,
      "YDS.1": 1,
      "TD.1": 0,
      "FL": 0,
      "REC": 2,
      "TGT": 2,
      "YDS.2": 14,
      "TD.2": 0,
      "G": 1,
      "FPTS": 3.5,
      "FPTS/G": 3.5,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Rachaad White",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Rachaad White",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  }
};
const fantasy_team_submissions = [
    {
        "name":"HolySchlitz!",
        "qb1":"Josh Allen",
        "qb2":"Jalen Hurts",
        "rb1":"Derrick Henry",
        "rb2":"Jahmyr Gibbs",
        "rb3":"Bucky Irving",
        "rb4":"Josh Jacobs",
        "wr1":"Travis Kelce",
        "wr2":"Terry McLaurin",
        "wr3":"Ladd McConkey",
        "wr4":"Justin Jefferson",
        "k1":"Ka'imi Fairbairn",
        "k2":"Chris Boswell",
        "def1":"Los Angeles Rams",
        "def2":"Denver Broncos",
        "tiebreak":48
    },
    {
        "name":"HolySchlitz!!",
        "qb1":"Josh Allen",
        "qb2":"Jared Goff",
        "rb1":"Saquon Barkley",
        "rb2":"Derrick Henry",
        "rb3":"Bucky Irving",
        "rb4":"Josh Jacobs",
        "wr1":"Nico Collins",
        "wr2":"Xavier Worthy",
        "wr3":"Puka Nacua",
        "wr4":"Justin Jefferson",
        "k1":"Chris Boswell",
        "k2":"Cameron Dicker",
        "def1":"Washington Commanders",
        "def2":"Denver Broncos",
        "tiebreak":65
    },
    {
        "name":"Yinz Stillers",
        "qb1":"Josh Allen",
        "qb2":"Patrick Mahomes II",
        "rb1":"Jahmyr Gibbs",
        "rb2":"Josh Jacobs",
        "rb3":"Derrick Henry",
        "rb4":"Saquon Barkley",
        "wr1":"Justin Jefferson",
        "wr2":"Mike Evans",
        "wr3":"Cooper Kupp",
        "wr4":"Terry McLaurin",
        "k1":"Chris Boswell",
        "k2":"Wil Lutz",
        "def1":"Houston Texans",
        "def2":"Los Angeles Chargers",
        "tiebreak":57
    },
    {
        "name":"RougeHeros",
        "qb1":"Lamar Jackson",
        "qb2":"Josh Allen",
        "rb1":"Saquon Barkley",
        "rb2":"Aaron Jones",
        "rb3":"Kareem Hunt",
        "rb4":"Najee Harris",
        "wr1":"Amon-Ra St. Brown",
        "wr2":"Diontae Johnson",
        "wr3":"George Kittle",
        "wr4":"Mike Evans",
        "k1":"Joshua Karty",
        "k2":"Zane Gonzalez",
        "def1":"Los Angeles Chargers",
        "def2":"Denver Broncos",
        "tiebreak":46
    },
    {
        "name":"M KIZ",
        "qb1":"Josh Allen",
        "qb2":"Lamar Jackson",
        "rb1":"Bucky Irving",
        "rb2":"Jahmyr Gibbs",
        "rb3":"J.K. Dobbins",
        "rb4":"Saquon Barkley",
        "wr1":"Nico Collins",
        "wr2":"Justin Jefferson",
        "wr3":"Xavier Worthy",
        "wr4":"Terry McLaurin",
        "k1":"Wil Lutz",
        "k2":"Chris Boswell",
        "def1":"Los Angeles Rams",
        "def2":"Green Bay Packers",
        "tiebreak":58
    },
    {
        "name":"E KIZ",
        "qb1":"Josh Allen",
        "qb2":"Patrick Mahomes II",
        "rb1":"Derrick Henry",
        "rb2":"Saquon Barkley",
        "rb3":"Kyren Williams",
        "rb4":"J.K. Dobbins",
        "wr1":"Amon-Ra St. Brown",
        "wr2":"Justin Jefferson",
        "wr3":"Mike Evans",
        "wr4":"Terry McLaurin",
        "k1":"Chris Boswell",
        "k2":"Wil Lutz",
        "def1":"Green Bay Packers",
        "def2":"Houston Texans",
        "tiebreak":54
    },
    {
        "name":"KEL-C",
        "qb1":"Josh Allen",
        "qb2":"Lamar Jackson",
        "rb1":"Saquon Barkley",
        "rb2":"Bucky Irving",
        "rb3":"Jahmyr Gibbs",
        "rb4":"Josh Jacobs",
        "wr1":"Puka Nacua",
        "wr2":"Ladd McConkey",
        "wr3":"Justin Jefferson",
        "wr4":"Travis Kelce",
        "k1":"Wil Lutz",
        "k2":"Ka'imi Fairbairn",
        "def1":"Washington Commanders",
        "def2":"Pittsburgh Steelers",
        "tiebreak":47
    },
    {
        "name":"Superbowl Shufflers",
        "qb1":"Josh Allen",
        "qb2":"Baker Mayfield",
        "rb1":"Jahmyr Gibbs",
        "rb2":"Saquon Barkley",
        "rb3":"Derrick Henry",
        "rb4":"Joe Mixon",
        "wr1":"Travis Kelce",
        "wr2":"Puka Nacua",
        "wr3":"Ladd McConkey",
        "wr4":"Romeo Doubs",
        "k1":"Wil Lutz",
        "k2":"Wil Reichard",
        "def1":"Pittsburgh Steelers",
        "def2":"Washington Commanders",
        "tiebreak":37
    },
    {
        "name":"Brutus1",
        "qb1":"Josh Allen",
        "qb2":"Lamar Jackson",
        "rb1":"Saquon Barkley",
        "rb2":"Jahmyr Gibbs",
        "rb3":"Joe Mixon",
        "rb4":"Isiah Pacheco",
        "wr1":"Puka Nacua",
        "wr2":"Mike Evans",
        "wr3":"Justin Jefferson",
        "wr4":"Ladd McConkey",
        "k1":"Brandon McManus",
        "k2":"Chris Boswell",
        "def1":"Washington Commanders",
        "def2":"Denver Broncos",
        "tiebreak":55
    },
    {
        "name":"Stallions",
        "qb1":"Josh Allen",
        "qb2":"Jared Goff",
        "rb1":"Saquon Barkley",
        "rb2":"Kyren Williams",
        "rb3":"Derrick Henry",
        "rb4":"Josh Jacobs",
        "wr1":"Mike Evans",
        "wr2":"Justin Jefferson",
        "wr3":"Courtland Sutton",
        "wr4":"Terry McLaurin",
        "k1":"Ka'imi Fairbairn",
        "k2":"Chris Boswell",
        "def1":"Kansas City Chiefs",
        "def2":"Los Angeles Chargers",
        "tiebreak":50
    },
    {
        "name":"Dina's Team",
        "qb1":"Patrick Mahomes II",
        "qb2":"Josh Allen",
        "rb1":"Derrick Henry",
        "rb2":"Jahmyr Gibbs",
        "rb3":"Saquon Barkley",
        "rb4":"J.K. Dobbins",
        "wr1":"Justin Jefferson",
        "wr2":"Courtland Sutton",
        "wr3":"Terry McLaurin",
        "wr4":"Mike Evans",
        "k1":"Ka'imi Fairbairn",
        "k2":"Brandon McManus",
        "def1":"Pittsburgh Steelers",
        "def2":"Los Angeles Rams",
        "tiebreak":47
    },
    {
        "name":"Berkeley Bulldogs",
        "qb1":"Josh Allen",
        "qb2":"Lamar Jackson",
        "rb1":"Jahmyr Gibbs",
        "rb2":"Saquon Barkley",
        "rb3":"Bucky Irving",
        "rb4":"J.K. Dobbins",
        "wr1":"Puka Nacua",
        "wr2":"Justin Jefferson",
        "wr3":"Nico Collins",
        "wr4":"Travis Kelce",
        "k1":"Zane Gonzalez",
        "k2":"Brandon McManus",
        "def1":"Pittsburgh Steelers",
        "def2":"Denver Broncos",
        "tiebreak":51
    },
    {
        "name":"Master Baker",
        "qb1":"Baker Mayfield",
        "qb2":"Josh Allen",
        "rb1":"Jahmyr Gibbs",
        "rb2":"Saquon Barkley",
        "rb3":"Derrick Henry",
        "rb4":"Kyren Williams",
        "wr1":"Travis Kelce",
        "wr2":"Justin Jefferson",
        "wr3":"Nico Collins",
        "wr4":"Ladd McConkey",
        "k1":"Zane Gonzalez",
        "k2":"Brandon McManus",
        "def1":"Denver Broncos",
        "def2":"Pittsburgh Steelers",
        "tiebreak":52
    },
    {
        "name":"Rookie Year",
        "qb1":"Jayden Daniels",
        "qb2":"Josh Allen",
        "rb1":"Derrick Henry",
        "rb2":"Joe Mixon",
        "rb3":"Jahmyr Gibbs",
        "rb4":"Saquon Barkley",
        "wr1":"Mike Evans",
        "wr2":"Xavier Worthy",
        "wr3":"Justin Jefferson",
        "wr4":"Puka Nacua",
        "k1":"Brandon McManus",
        "k2":"Cameron Dicker",
        "def1":"Denver Broncos",
        "def2":"Pittsburgh Steelers",
        "tiebreak":49
    },
    {
        "name":"WhoaNelly33",
        "qb1":"Josh Allen",
        "qb2":"Lamar Jackson",
        "rb1":"Bucky Irving",
        "rb2":"Jahmyr Gibbs",
        "rb3":"Saquon Barkley",
        "rb4":"Kyren Williams",
        "wr1":"Justin Jefferson",
        "wr2":"Travis Kelce",
        "wr3":"Ladd McConkey",
        "wr4":"Terry McLaurin",
        "k1":"Brandon McManus",
        "k2":"Ka'imi Fairbairn",
        "def1":"Denver Broncos",
        "def2":"Pittsburgh Steelers",
        "tiebreak":49
    },
    {
        "name":"Southpaws",
        "qb1":"Josh Allen",
        "qb2":"Lamar Jackson",
        "rb1":"Saquon Barkley",
        "rb2":"Javonte Williams",
        "rb3":"Jahmyr Gibbs",
        "rb4":"Bucky Irving",
        "wr1":"Travis Kelce",
        "wr2":"Puka Nacua",
        "wr3":"Justin Jefferson",
        "wr4":"Nico Collins",
        "k1":"Brandon McManus",
        "k2":"Chris Boswell",
        "def1":"Los Angeles Chargers",
        "def2":"Washington Commanders",
        "tiebreak":57
    },
    {
        "name":"Hawks",
        "qb1":"Lamar Jackson",
        "qb2":"Patrick Mahomes II",
        "rb1":"James Cook",
        "rb2":"Jahmyr Gibbs",
        "rb3":"Saquon Barkley",
        "rb4":"Josh Jacobs",
        "wr1":"Mike Evans",
        "wr2":"Puka Nacua",
        "wr3":"Justin Jefferson",
        "wr4":"Terry McLaurin",
        "k1":"Chris Boswell",
        "k2":"Wil Lutz",
        "def1":"Houston Texans",
        "def2":"Los Angeles Chargers",
        "tiebreak":58
    },
    {
        "name":"SundayBloodySunday",
        "qb1":"Josh Allen",
        "qb2":"Jared Goff",
        "rb1":"Derrick Henry",
        "rb2":"Saquon Barkley",
        "rb3":"Isiah Pacheco",
        "rb4":"Bucky Irving",
        "wr1":"Justin Jefferson",
        "wr2":"Terry McLaurin",
        "wr3":"Ladd McConkey",
        "wr4":"Puka Nacua",
        "k1":"Chris Boswell",
        "k2":"Brandon McManus",
        "def1":"Houston Texans",
        "def2":"Denver Broncos",
        "tiebreak":45
    },
    {
        "name":"Big Winner ",
        "qb1":"Lamar Jackson",
        "qb2":"Josh Allen",
        "rb1":"Saquon Barkley",
        "rb2":"Bucky Irving",
        "rb3":"Jahmyr Gibbs",
        "rb4":"Josh Jacobs",
        "wr1":"Puka Nacua",
        "wr2":"Ladd McConkey",
        "wr3":"Xavier Worthy",
        "wr4":"Nico Collins",
        "k1":"Zane Gonzalez",
        "k2":"Chris Boswell",
        "def1":"Denver Broncos",
        "def2":"Minnesota Vikings",
        "tiebreak":51
    },
    {
        "name":"T &T Skokie",
        "qb1":"Josh Allen",
        "qb2":"Jared Goff",
        "rb1":"Derrick Henry",
        "rb2":"Saquon Barkley",
        "rb3":"J.K. Dobbins",
        "rb4":"Josh Jacobs",
        "wr1":"Puka Nacua",
        "wr2":"Nico Collins",
        "wr3":"Justin Jefferson",
        "wr4":"Travis Kelce",
        "k1":"Wil Lutz",
        "k2":"Chris Boswell",
        "def1":"Tampa Bay Buccaneers",
        "def2":"Washington Commanders",
        "tiebreak":49
    },
    {
        "name":"TB Skokie ",
        "qb1":"Patrick Mahomes II",
        "qb2":"Lamar Jackson",
        "rb1":"Saquon Barkley",
        "rb2":"Bucky Irving",
        "rb3":"James Cook",
        "rb4":"Brian Robinson Jr.",
        "wr1":"Amon-Ra St. Brown",
        "wr2":"Justin Jefferson",
        "wr3":"Cooper Kupp",
        "wr4":"Ladd McConkey",
        "k1":"Ka'imi Fairbairn",
        "k2":"Chris Boswell",
        "def1":"Denver Broncos",
        "def2":"Green Bay Packers",
        "tiebreak":50
    },
    {
        "name":"Mac's Team",
        "qb1":"Jared Goff",
        "qb2":"Lamar Jackson",
        "rb1":"Saquon Barkley",
        "rb2":"Kareem Hunt",
        "rb3":"Joe Mixon",
        "rb4":"Bucky Irving",
        "wr1":"Justin Jefferson",
        "wr2":"Cooper Kupp",
        "wr3":"George Pickens",
        "wr4":"Amari Cooper",
        "k1":"Brandon McManus",
        "k2":"Wil Lutz",
        "def1":"Washington Commanders",
        "def2":"Los Angeles Chargers",
        "tiebreak":48
    },
    {
        "name":"Pathetic Team",
        "qb1":"Josh Allen",
        "qb2":"Patrick Mahomes II",
        "rb1":"Jahmyr Gibbs",
        "rb2":"Derrick Henry",
        "rb3":"Josh Jacobs",
        "rb4":"Saquon Barkley",
        "wr1":"Courtland Sutton",
        "wr2":"Justin Jefferson",
        "wr3":"Puka Nacua",
        "wr4":"Terry McLaurin",
        "k1":"Chase McLaughlin",
        "k2":"Cameron Dicker",
        "def1":"Houston Texans",
        "def2":"Pittsburgh Steelers",
        "tiebreak":55
    },
    {
        "name":"Pathetic Team 2",
        "qb1":"Josh Allen",
        "qb2":"Jayden Daniels",
        "rb1":"Saquon Barkley",
        "rb2":"Jahmyr Gibbs",
        "rb3":"Derrick Henry",
        "rb4":"Kyren Williams",
        "wr1":"Justin Jefferson",
        "wr2":"Nico Collins",
        "wr3":"George Pickens",
        "wr4":"Courtland Sutton",
        "k1":"Chase McLaughlin",
        "k2":"Cameron Dicker",
        "def1":"Kansas City Chiefs",
        "def2":"Green Bay Packers",
        "tiebreak":52
    },
    {
        "name":"Suck my Ditka",
        "qb1":"Josh Allen",
        "qb2":"Patrick Mahomes II",
        "rb1":"Derrick Henry",
        "rb2":"Jahmyr Gibbs",
        "rb3":"Saquon Barkley",
        "rb4":"Bucky Irving",
        "wr1":"Ladd McConkey",
        "wr2":"Justin Jefferson",
        "wr3":"Puka Nacua",
        "wr4":"Terry McLaurin",
        "k1":"Wil Lutz",
        "k2":"Brandon McManus",
        "def1":"Pittsburgh Steelers",
        "def2":"Houston Texans",
        "tiebreak":66
    },
    {
        "name":"The Bears will mess it up again",
        "qb1":"Jared Goff",
        "qb2":"Lamar Jackson",
        "rb1":"James Cook",
        "rb2":"Saquon Barkley",
        "rb3":"Kyren Williams",
        "rb4":"Joe Mixon",
        "wr1":"Mike Evans",
        "wr2":"Courtland Sutton",
        "wr3":"Justin Jefferson",
        "wr4":"Terry McLaurin",
        "k1":"Harrison Butker",
        "k2":"Brandon McManus",
        "def1":"Los Angeles Chargers",
        "def2":"Pittsburgh Steelers",
        "tiebreak":59
    },
    {
        "name":"Little Metro\u2019s team",
        "qb1":"Jayden Daniels",
        "qb2":"Lamar Jackson",
        "rb1":"Jahmyr Gibbs",
        "rb2":"Bucky Irving",
        "rb3":"James Cook",
        "rb4":"Kyren Williams",
        "wr1":"A.J. Brown",
        "wr2":"Travis Kelce",
        "wr3":"Nico Collins",
        "wr4":"Ladd McConkey",
        "k1":"Chris Boswell",
        "k2":"Wil Reichard",
        "def1":"Green Bay Packers",
        "def2":"Denver Broncos",
        "tiebreak":55
    },
    {
        "name":"Lemonheads",
        "qb1":"Josh Allen",
        "qb2":"Lamar Jackson",
        "rb1":"Jahmyr Gibbs",
        "rb2":"Josh Jacobs",
        "rb3":"Kyren Williams",
        "rb4":"Saquon Barkley",
        "wr1":"Justin Jefferson",
        "wr2":"Travis Kelce",
        "wr3":"Nico Collins",
        "wr4":"Ladd McConkey",
        "k1":"Chris Boswell",
        "k2":"Wil Lutz",
        "def1":"Tampa Bay Buccaneers",
        "def2":"Washington Commanders",
        "tiebreak":58
    },
    {
        "name":"CraftingRunning",
        "qb1":"Josh Allen",
        "qb2":"Baker Mayfield",
        "rb1":"Austin Ekeler",
        "rb2":"Derrick Henry",
        "rb3":"Joe Mixon",
        "rb4":"Najee Harris",
        "wr1":"JuJu Smith-Schuster",
        "wr2":"Amon-Ra St. Brown",
        "wr3":"DeVonta Smith",
        "wr4":"Jordan Addison",
        "k1":"Wil Lutz",
        "k2":"Brandon McManus",
        "def1":"Los Angeles Chargers",
        "def2":"Los Angeles Rams",
        "tiebreak":65
    },
    {
        "name":"Hitmen (M Dierbach)",
        "qb1":"Josh Allen",
        "qb2":"Jared Goff",
        "rb1":"Derrick Henry",
        "rb2":"Saquon Barkley",
        "rb3":"Bucky Irving",
        "rb4":"Josh Jacobs",
        "wr1":"Justin Jefferson",
        "wr2":"Terry McLaurin",
        "wr3":"Travis Kelce",
        "wr4":"Ladd McConkey",
        "k1":"Ka'imi Fairbairn",
        "k2":"Joshua Karty",
        "def1":"Denver Broncos",
        "def2":"Pittsburgh Steelers",
        "tiebreak":45
    },
    {
        "name":"Hitmen 2 (M Dierbach)",
        "qb1":"Lamar Jackson",
        "qb2":"Josh Allen",
        "rb1":"Saquon Barkley",
        "rb2":"Bucky Irving",
        "rb3":"Kyren Williams",
        "rb4":"Jahmyr Gibbs",
        "wr1":"Terry McLaurin",
        "wr2":"Justin Jefferson",
        "wr3":"Travis Kelce",
        "wr4":"Nico Collins",
        "k1":"Cameron Dicker",
        "k2":"Brandon McManus",
        "def1":"Denver Broncos",
        "def2":"Pittsburgh Steelers",
        "tiebreak":38
    },
    {
        "name":"BNelly",
        "qb1":"Josh Allen",
        "qb2":"Lamar Jackson",
        "rb1":"Saquon Barkley",
        "rb2":"Jahmyr Gibbs",
        "rb3":"Kyren Williams",
        "rb4":"Bucky Irving",
        "wr1":"Justin Jefferson",
        "wr2":"Travis Kelce",
        "wr3":"Terry McLaurin",
        "wr4":"Ladd McConkey",
        "k1":"Chris Boswell",
        "k2":"Brandon McManus",
        "def1":"Denver Broncos",
        "def2":"Houston Texans",
        "tiebreak":55
    },
    {
        "name":"Cdierbach",
        "qb1":"Patrick Mahomes II",
        "qb2":"Josh Allen",
        "rb1":"Josh Jacobs",
        "rb2":"Derrick Henry",
        "rb3":"Saquon Barkley",
        "rb4":"Jahmyr Gibbs",
        "wr1":"George Pickens",
        "wr2":"Cooper Kupp",
        "wr3":"Nico Collins",
        "wr4":"Terry McLaurin",
        "k1":"Cameron Dicker",
        "k2":"Chase McLaughlin",
        "def1":"Denver Broncos",
        "def2":"Minnesota Vikings",
        "tiebreak":45
    },
    {
        "name":"Pukkake",
        "qb1":"Josh Allen",
        "qb2":"Lamar Jackson",
        "rb1":"Saquon Barkley",
        "rb2":"Jahmyr Gibbs",
        "rb3":"Josh Jacobs",
        "rb4":"Bucky Irving",
        "wr1":"Puka Nacua",
        "wr2":"Nico Collins",
        "wr3":"Ladd McConkey",
        "wr4":"Justin Jefferson",
        "k1":"Chris Boswell",
        "k2":"Zane Gonzalez",
        "def1":"Kansas City Chiefs",
        "def2":"Denver Broncos",
        "tiebreak":46
    },
    {
        "name":"Nash Dawgs",
        "qb1":"Lamar Jackson",
        "qb2":"Jalen Hurts",
        "rb1":"Brian Robinson Jr.",
        "rb2":"Josh Jacobs",
        "rb3":"James Cook",
        "rb4":"Joe Mixon",
        "wr1":"Ladd McConkey",
        "wr2":"Amon-Ra St. Brown",
        "wr3":"Justin Jefferson",
        "wr4":"Puka Nacua",
        "k1":"Wil Lutz",
        "k2":"Chris Boswell",
        "def1":"Kansas City Chiefs",
        "def2":"Tampa Bay Buccaneers",
        "tiebreak":56
    },
    {
        "name":"Nash Dawgs 2",
        "qb1":"Lamar Jackson",
        "qb2":"Patrick Mahomes II",
        "rb1":"Saquon Barkley",
        "rb2":"Bucky Irving",
        "rb3":"James Cook",
        "rb4":"Josh Jacobs",
        "wr1":"Justin Jefferson",
        "wr2":"Nico Collins",
        "wr3":"Puka Nacua",
        "wr4":"Amon-Ra St. Brown",
        "k1":"Cameron Dicker",
        "k2":"Zane Gonzalez",
        "def1":"Pittsburgh Steelers",
        "def2":"Denver Broncos",
        "tiebreak":64
    },
    {
        "name":"Bakers Dozen",
        "qb1":"Josh Allen",
        "qb2":"Baker Mayfield",
        "rb1":"Jahmyr Gibbs",
        "rb2":"Derrick Henry",
        "rb3":"Saquon Barkley",
        "rb4":"Josh Jacobs",
        "wr1":"Justin Jefferson",
        "wr2":"Ladd McConkey",
        "wr3":"Travis Kelce",
        "wr4":"Puka Nacua",
        "k1":"Chris Boswell",
        "k2":"Zane Gonzalez",
        "def1":"Houston Texans",
        "def2":"Denver Broncos",
        "tiebreak":52
    },
    {
        "name":"Mason's Team",
        "qb1":"Jared Goff",
        "qb2":"Lamar Jackson",
        "rb1":"James Cook",
        "rb2":"Saquon Barkley",
        "rb3":"Joe Mixon",
        "rb4":"Josh Jacobs",
        "wr1":"Puka Nacua",
        "wr2":"Justin Jefferson",
        "wr3":"Ladd McConkey",
        "wr4":"DeAndre Hopkins",
        "k1":"Chase McLaughlin",
        "k2":"Wil Lutz",
        "def1":"Pittsburgh Steelers",
        "def2":"Washington Commanders",
        "tiebreak":52
    },
    {
        "name":"Southpaws2",
        "qb1":"Josh Allen",
        "qb2":"Jared Goff",
        "rb1":"Derrick Henry",
        "rb2":"Rachaad White",
        "rb3":"Saquon Barkley",
        "rb4":"Austin Ekeler",
        "wr1":"Jordan Addison",
        "wr2":"Nico Collins",
        "wr3":"Puka Nacua",
        "wr4":"George Pickens",
        "k1":"Wil Lutz",
        "k2":"Brandon McManus",
        "def1":"Los Angeles Chargers",
        "def2":"Kansas City Chiefs",
        "tiebreak":57
    }
];
    