const player_stats = {
  "Saquon Barkley": {
    "week 1": {
      "Rank": 0,
      "Player": "Saquon Barkley",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "89.7%",
      "POS": "qb"
    }
  },
  "Justin Jefferson": {
    "week 1": {
      "Rank": 0,
      "Player": "Justin Jefferson",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "82.1%",
      "POS": "qb"
    }
  },
  "Josh Allen": {
    "week 1": {
      "Rank": 0,
      "Player": "Josh Allen",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "79.5%",
      "POS": "qb"
    }
  },
  "Jahmyr Gibbs": {
    "week 1": {
      "Rank": 0,
      "Player": "Jahmyr Gibbs",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "61.5%",
      "POS": "qb"
    }
  },
  "Lamar Jackson": {
    "week 1": {
      "Rank": 0,
      "Player": "Lamar Jackson",
      "CMP": 16,
      "ATT": 21,
      "PCT": 76.2,
      "YDS": 175,
      "TD": 2,
      "INT": 0,
      "ATT.1": 15,
      "YDS.1": 81,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 23.1,
      "FPTS/G": 23.1,
      "ROST": "51.3%",
      "POS": "qb"
    }
  },
  "Derrick Henry": {
    "week 1": {
      "Rank": 0,
      "Player": "Derrick Henry",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 26,
      "YDS.1": 186,
      "TD.1": 2,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 30.6,
      "FPTS/G": 30.6,
      "ROST": "48.7%",
      "POS": "qb"
    }
  },
  "Chris Boswell": {
    "week 1": {
      "Rank": 0,
      "Player": "Chris Boswell",
      "FPTS": 2,
      "FPTS/G": 2,
      "ROST": "48.7%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Chris Boswell",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "48.7%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Chris Boswell",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "48.7%",
      "POS": "k"
    },
    "week 4": {
      "Rank": 0,
      "Player": "Chris Boswell",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "48.7%",
      "POS": "k"
    }
  },
  "Denver Broncos": {
    "week 1": {
      "Rank": 0,
      "Player": "Denver Broncos",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "48.7%",
      "POS": "def"
    }
  },
  "Puka Nacua": {
    "week 1": {
      "Rank": 0,
      "Player": "Puka Nacua",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "48.7%",
      "POS": "qb"
    }
  },
  "Bucky Irving": {
    "week 1": {
      "Rank": 0,
      "Player": "Bucky Irving",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "46.2%",
      "POS": "qb"
    }
  },
  "Ladd McConkey": {
    "week 1": {
      "Rank": 0,
      "Player": "Ladd McConkey",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 9,
      "TGT": 14,
      "YDS.2": 197,
      "TD.2": 1,
      "G": 1,
      "FPTS": 34.7,
      "FPTS/G": 34.7,
      "ROST": "46.2%",
      "POS": "wr"
    }
  },
  "Josh Jacobs": {
    "week 1": {
      "Rank": 0,
      "Player": "Josh Jacobs",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "43.6%",
      "POS": "qb"
    }
  },
  "Terry McLaurin": {
    "week 1": {
      "Rank": 0,
      "Player": "Terry McLaurin",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "41.0%",
      "POS": "qb"
    }
  },
  "Nico Collins": {
    "week 1": {
      "Rank": 0,
      "Player": "Nico Collins",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 7,
      "TGT": 8,
      "YDS.2": 122,
      "TD.2": 1,
      "G": 1,
      "FPTS": 25.2,
      "FPTS/G": 25.2,
      "ROST": "38.5%",
      "POS": "wr"
    }
  },
  "Brandon McManus": {
    "week 1": {
      "Rank": 0,
      "Player": "Brandon McManus",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "38.5%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Brandon McManus",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "38.5%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Brandon McManus",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "38.5%",
      "POS": "k"
    },
    "week 4": {
      "Rank": 0,
      "Player": "Brandon McManus",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "38.5%",
      "POS": "k"
    }
  },
  "Travis Kelce": {
    "week 1": {
      "Rank": 0,
      "Player": "Travis Kelce",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "35.9%",
      "POS": "qb"
    }
  },
  "Wil Lutz": {
    "week 1": {
      "Rank": 0,
      "Player": "Wil Lutz",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "35.9%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Wil Lutz",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "35.9%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Wil Lutz",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "35.9%",
      "POS": "k"
    },
    "week 4": {
      "Rank": 0,
      "Player": "Wil Lutz",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "35.9%",
      "POS": "k"
    }
  },
  "Pittsburgh Steelers": {
    "week 1": {
      "Rank": 0,
      "Player": "Pittsburgh Steelers",
      "SACKS": 1.0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 28,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "35.9%",
      "POS": "def"
    }
  },
  "Kyren Williams": {
    "week 1": {
      "Rank": 0,
      "Player": "Kyren Williams",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "25.6%",
      "POS": "qb"
    }
  },
  "Jared Goff": {
    "week 1": {
      "Rank": 0,
      "Player": "Jared Goff",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "23.1%",
      "POS": "qb"
    }
  },
  "Washington Commanders": {
    "week 1": {
      "Rank": 0,
      "Player": "Washington Commanders",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "23.1%",
      "POS": "def"
    }
  },
  "Patrick Mahomes II": {
    "week 1": {
      "Rank": 0,
      "Player": "Patrick Mahomes II",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "23.1%",
      "POS": "qb"
    }
  },
  "Mike Evans": {
    "week 1": {
      "Rank": 0,
      "Player": "Mike Evans",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "23.1%",
      "POS": "qb"
    }
  },
  "Los Angeles Chargers": {
    "week 1": {
      "Rank": 0,
      "Player": "Los Angeles Chargers",
      "SACKS": 3.0,
      "FR": 2,
      "INT.1": 1,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 32,
      "G": 1,
      "FPTS": 8.0,
      "FPTS/G": 8.0,
      "ROST": "23.1%",
      "POS": "def"
    }
  },
  "Houston Texans": {
    "week 1": {
      "Rank": 0,
      "Player": "Houston Texans",
      "SACKS": 4.0,
      "FR": 0,
      "INT.1": 4,
      "TD.3": 1,
      "BK": 0,
      "SAFE": 0,
      "PA": 12,
      "G": 1,
      "FPTS": 22.0,
      "FPTS/G": 22.0,
      "ROST": "20.5%",
      "POS": "def"
    }
  },
  "Joe Mixon": {
    "week 1": {
      "Rank": 0,
      "Player": "Joe Mixon",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 25,
      "YDS.1": 106,
      "TD.1": 1,
      "FL": 0,
      "REC": 1,
      "TGT": 2,
      "YDS.2": 13,
      "TD.2": 0,
      "G": 1,
      "FPTS": 18.9,
      "FPTS/G": 18.9,
      "ROST": "20.5%",
      "POS": "wr"
    }
  },
  "Ka'imi Fairbairn": {
    "week 1": {
      "Rank": 0,
      "Player": "Ka'imi Fairbairn",
      "FPTS": 13,
      "FPTS/G": 13,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Ka'imi Fairbairn",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Ka'imi Fairbairn",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 4": {
      "Rank": 0,
      "Player": "Ka'imi Fairbairn",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "17.9%",
      "POS": "k"
    }
  },
  "Cameron Dicker": {
    "week 1": {
      "Rank": 0,
      "Player": "Cameron Dicker",
      "FPTS": 6,
      "FPTS/G": 6,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Cameron Dicker",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Cameron Dicker",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 4": {
      "Rank": 0,
      "Player": "Cameron Dicker",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "17.9%",
      "POS": "k"
    }
  },
  "Austin Seibert": {
    "week 1": {
      "Rank": 0,
      "Player": "Austin Seibert",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Austin Seibert",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Austin Seibert",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "17.9%",
      "POS": "k"
    },
    "week 4": {
      "Rank": 0,
      "Player": "Austin Seibert",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "17.9%",
      "POS": "k"
    }
  },
  "James Cook": {
    "week 1": {
      "Rank": 0,
      "Player": "James Cook",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "17.9%",
      "POS": "qb"
    }
  },
  "Amon-Ra St. Brown": {
    "week 1": {
      "Rank": 0,
      "Player": "Amon-Ra St. Brown",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "15.4%",
      "POS": "qb"
    }
  },
  "J.K. Dobbins": {
    "week 1": {
      "Rank": 0,
      "Player": "J.K. Dobbins",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 9,
      "YDS.1": 26,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 2.6,
      "FPTS/G": 2.6,
      "ROST": "12.8%",
      "POS": "rb"
    }
  },
  "Green Bay Packers": {
    "week 1": {
      "Rank": 0,
      "Player": "Green Bay Packers",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "12.8%",
      "POS": "def"
    }
  },
  "Courtland Sutton": {
    "week 1": {
      "Rank": 0,
      "Player": "Courtland Sutton",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "12.8%",
      "POS": "qb"
    }
  },
  "Kansas City Chiefs": {
    "week 1": {
      "Rank": 0,
      "Player": "Kansas City Chiefs",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "12.8%",
      "POS": "def"
    }
  },
  "Los Angeles Rams": {
    "week 1": {
      "Rank": 0,
      "Player": "Los Angeles Rams",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "10.3%",
      "POS": "def"
    }
  },
  "Xavier Worthy": {
    "week 1": {
      "Rank": 0,
      "Player": "Xavier Worthy",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "10.3%",
      "POS": "qb"
    }
  },
  "Cooper Kupp": {
    "week 1": {
      "Rank": 0,
      "Player": "Cooper Kupp",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "10.3%",
      "POS": "qb"
    }
  },
  "Baker Mayfield": {
    "week 1": {
      "Rank": 0,
      "Player": "Baker Mayfield",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "10.3%",
      "POS": "qb"
    }
  },
  "George Pickens": {
    "week 1": {
      "Rank": 0,
      "Player": "George Pickens",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 5,
      "TGT": 5,
      "YDS.2": 87,
      "TD.2": 1,
      "G": 1,
      "FPTS": 19.7,
      "FPTS/G": 19.7,
      "ROST": "10.3%",
      "POS": "qb"
    }
  },
  "Chase McLaughlin": {
    "week 1": {
      "Rank": 0,
      "Player": "Chase McLaughlin",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Chase McLaughlin",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Chase McLaughlin",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    },
    "week 4": {
      "Rank": 0,
      "Player": "Chase McLaughlin",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    }
  },
  "Jayden Daniels": {
    "week 1": {
      "Rank": 0,
      "Player": "Jayden Daniels",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "7.7%",
      "POS": "qb"
    }
  },
  "Tampa Bay Buccaneers": {
    "week 1": {
      "Rank": 0,
      "Player": "Tampa Bay Buccaneers",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "7.7%",
      "POS": "def"
    }
  },
  "Jalen Hurts": {
    "week 1": {
      "Rank": 0,
      "Player": "Jalen Hurts",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "5.1%",
      "POS": "qb"
    }
  },
  "Kareem Hunt": {
    "week 1": {
      "Rank": 0,
      "Player": "Kareem Hunt",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "5.1%",
      "POS": "qb"
    }
  },
  "Najee Harris": {
    "week 1": {
      "Rank": 0,
      "Player": "Najee Harris",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 6,
      "YDS.1": 17,
      "TD.1": 0,
      "FL": 0,
      "REC": 3,
      "TGT": 3,
      "YDS.2": 41,
      "TD.2": 0,
      "G": 1,
      "FPTS": 8.8,
      "FPTS/G": 8.8,
      "ROST": "5.1%",
      "POS": "qb"
    }
  },
  "Joshua Karty": {
    "week 1": {
      "Rank": 0,
      "Player": "Joshua Karty",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Joshua Karty",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Joshua Karty",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    },
    "week 4": {
      "Rank": 0,
      "Player": "Joshua Karty",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    }
  },
  "Wil Reichard": {
    "week 1": {
      "Rank": 0,
      "Player": "Wil Reichard",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Wil Reichard",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Wil Reichard",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    },
    "week 4": {
      "Rank": 0,
      "Player": "Wil Reichard",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    }
  },
  "Isiah Pacheco": {
    "week 1": {
      "Rank": 0,
      "Player": "Isiah Pacheco",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "5.1%",
      "POS": "qb"
    }
  },
  "Minnesota Vikings": {
    "week 1": {
      "Rank": 0,
      "Player": "Minnesota Vikings",
      "SACKS": 0,
      "FR": 0,
      "INT.1": 0,
      "TD.3": 0,
      "BK": 0,
      "SAFE": 0,
      "PA": 0,
      "G": 1,
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "5.1%",
      "POS": "def"
    }
  },
  "Brian Robinson Jr.": {
    "week 1": {
      "Rank": 0,
      "Player": "Brian Robinson Jr.",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "5.1%",
      "POS": "qb"
    }
  },
  "Austin Ekeler": {
    "week 1": {
      "Rank": 0,
      "Player": "Austin Ekeler",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "5.1%",
      "POS": "qb"
    }
  },
  "Jordan Addison": {
    "week 1": {
      "Rank": 0,
      "Player": "Jordan Addison",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "5.1%",
      "POS": "qb"
    }
  },
  "Aaron Jones": {
    "week 1": {
      "Rank": 0,
      "Player": "Aaron Jones",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "Diontae Johnson": {
    "week 1": {
      "Rank": 0,
      "Player": "Diontae Johnson",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 1,
      "TGT": 1,
      "YDS.2": 12,
      "TD.2": 0,
      "G": 1,
      "FPTS": 2.2,
      "FPTS/G": 2.2,
      "ROST": "2.6%",
      "POS": "wr"
    }
  },
  "George Kittle": {
    "week 1": {
      "Rank": 0,
      "Player": "George Kittle",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "Romeo Doubs": {
    "week 1": {
      "Rank": 0,
      "Player": "Romeo Doubs",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "Javonte Williams": {
    "week 1": {
      "Rank": 0,
      "Player": "Javonte Williams",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "Amari Cooper": {
    "week 1": {
      "Rank": 0,
      "Player": "Amari Cooper",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "Harrison Butker": {
    "week 1": {
      "Rank": 0,
      "Player": "Harrison Butker",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    },
    "week 2": {
      "Rank": 0,
      "Player": "Harrison Butker",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    },
    "week 3": {
      "Rank": 0,
      "Player": "Harrison Butker",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    },
    "week 4": {
      "Rank": 0,
      "Player": "Harrison Butker",
      "FPTS": 0,
      "FPTS/G": 0,
      "ROST": "0%",
      "POS": "k"
    }
  },
  "A.J. Brown": {
    "week 1": {
      "Rank": 0,
      "Player": "A.J. Brown",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "JuJu Smith-Schuster": {
    "week 1": {
      "Rank": 0,
      "Player": "JuJu Smith-Schuster",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "DeVonta Smith": {
    "week 1": {
      "Rank": 0,
      "Player": "DeVonta Smith",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "DeAndre Hopkins": {
    "week 1": {
      "Rank": 0,
      "Player": "DeAndre Hopkins",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  },
  "Rachaad White": {
    "week 1": {
      "Rank": 0,
      "Player": "Rachaad White",
      "CMP": 0,
      "ATT": 0,
      "PCT": 0,
      "YDS": 0,
      "TD": 0,
      "INT": 0,
      "ATT.1": 0,
      "YDS.1": 0,
      "TD.1": 0,
      "FL": 0,
      "REC": 0,
      "TGT": 0,
      "YDS.2": 0,
      "TD.2": 0,
      "G": 1,
      "FPTS": 0.0,
      "FPTS/G": 0.0,
      "ROST": "2.6%",
      "POS": "qb"
    }
  }
};